// StringSerializationAPI.cs
//
//  Author:
//       Roman Feshchenko <roman.feshchenko@meliorgames.com>
//  Created:
//      08/14/2015
//
//  Copyright (c) 2015 
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using FullSerializer;

public static class JSonSerializer 
{
	private static readonly fsSerializer _serializer = new fsSerializer();
	
	public static string Serialize(object value, bool isCompressed = true) 
	{
		fsData data;
		_serializer.TrySerialize(value.GetType(), value, out data).AssertSuccessWithoutWarnings();
		
		if(isCompressed)
		{
			return fsJsonPrinter.CompressedJson(data);
		}

		return fsJsonPrinter.PrettyJson(data);
	}
	
	public static T Deserialize<T>(string jsonSerializedObject) 
	{
		fsData data = fsJsonParser.Parse(jsonSerializedObject);
		object deserialized = null;
		_serializer.TryDeserialize(data, typeof(T), ref deserialized).AssertSuccess();
		return (T)deserialized;
	}
}