//
// SerializableHashSet.cs
//
//  Author:
//       Nikita Skvorchinsky <nikita.skvorchinsky@meliorgames.com>
//  Created:
//      06/18/2015
//
//  Copyright (c) 2015 
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace DotOriko.Data.Serialization
{
	[Serializable]
	public class SerializableHashSet<T>:HashSet<T>,ISerializable
	{
		#region ISerializable implementation
		
		public new void GetObjectData (SerializationInfo info, StreamingContext context)
		{
			info.AddValue("1", new List<T>(this).ToArray());
		}
		
		#endregion
		
		public SerializableHashSet(SerializationInfo info, StreamingContext context)
		{
			T[] array = (T[])info.GetValue("1",typeof(T[]));

			foreach (T item in array)
			{
				Add( item );
			}
		}
		
		public SerializableHashSet ()
		{
		}
	}
}