//
// EnumUtils.cs
//
//  Author:
//       Nikita Skvorchinsky <nikita.skvorchinsky@meliorgames.com>
//  Created:
//      02/26/2015
//
//  Copyright (c) 2015 
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Reflection;
using LinqTools;

public static class EnumUtils
{
	public static Boolean HasAttribute<T>(this Enum enumValue) where T: Attribute
	{
		MemberInfo memberInfo = enumValue.GetType().GetMember(enumValue.ToString())
			.FirstOrDefault();

		if (memberInfo != null)
		{
			return null != memberInfo.GetCustomAttributes(typeof (T), false).FirstOrDefault();
		}
		return false;
	}
}