// NetworkUtils.cs
//
//  Author:
//       Roman Feshchenko <roman.feshchenko@meliorgames.com>
//  Created:
//      09/14/2015
//
//  Copyright (c) 2015 
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public static class NetworkUtils
{
	private const string kCheckupUrlAddress = "https://parse.com";

	public static bool CheckForInternetConnection()
	{
		try
		{
			using (System.Net.WebClient client = new System.Net.WebClient())
			{
				using (System.IO.Stream stream = client.OpenRead(kCheckupUrlAddress))
				{
					return true;
				}
			}
		}
		catch
		{
			return false;
		}
	}
}